amcl:
  ros__parameters:
    use_sim_time: false

    base_frame_id: "base_link"
    odom_frame_id: "odom"
    global_frame_id: "map"
    scan_topic: /scan_fullframe

    tf_broadcast: true
    transform_tolerance: 0.5

    min_particles: 500
    max_particles: 2000
    resample_interval: 1

    laser_model_type: "likelihood_field"
    max_beams: 60
    z_hit: 0.5
    z_short: 0.05
    z_max: 0.05
    z_rand: 0.5
    sigma_hit: 0.2
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0

    update_min_d: 0.10
    update_min_a: 0.10

    recovery_alpha_slow: 0.0
    recovery_alpha_fast: 0.0

    set_initial_pose: false
    first_map_only: false
    save_pose_rate: 0.5