<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>flex_bot_bringup</name>
  <version>0.0.0</version>
  <description>Bringup package for FlexBot mapping and localization</description>
  <maintainer email="kartik8virmani@gmail.com">kartik</maintainer>
  <license>MIT</license>

  <depend>rclpy</depend>
  <depend>launch</depend>
  <depend>launch_ros</depend>
  <depend>ament_index_python</depend>

  <depend>tf2_ros</depend>
  <depend>robot_localization</depend>
  <depend>rviz2</depend>

  <depend>sensor_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>geometry_msgs</depend>

  <depend>nav2_amcl</depend>
  <depend>nav2_map_server</depend>
  <depend>nav2_lifecycle_manager</depend>

  <depend>cartographer_ros</depend>
  <depend>slam_toolbox</depend>

  <depend>sick_scan_xd</depend>

  <exec_depend>flex_bot_odometry</exec_depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>